on:
  schedule:
  - cron: "0 13 * * *"
jobs:
 run-uptime:
    runs-on: ubuntu-latest
    steps:
    - name: Uptime Action
      uses: srt32/uptime@v0.2.1
      with:
        # which url to hit
        url-to-hit:  "https://unpkg.com/tone@14.7.77/build/Tone.js"
        # which http response statuses are expected
        expected-statuses: "200"
